import Head from 'next/head'
import Link from 'next/link'
import { Heading, Flex, Stack, Divider } from '@chakra-ui/react'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import { ContentBanner } from '../../components/ContentBanner'

interface LessonProps {
  lessons: {
    frontMatter: any
    slug: string
  }[]
}

const Lessons: React.FC<LessonProps> = ({ lessons }) => {
  return (
    <>
      <Head>
        <title>D_D School of Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex as="main" py={5} px={[4, 10, 16]} direction="column">
        <Stack spacing={5} direction="column">
          <Heading
            fontSize={['md', 'lg']}
            as="h2"
            textAlign="center"
            color="#F96C9D"
          >
            GETTING STARTED
          </Heading>
          <Heading fontSize={['xs', 'sm']} as="h3" textAlign="center">
            How it started (Introduction to project)
          </Heading>
          <Divider />
          <Heading fontSize={['xs', 'sm']} as="h3" textAlign="center">
            Highlights of Resources
          </Heading>
          <Divider />
          <Heading fontSize={['xs', 'sm']} as="h3" textAlign="center">
            Roadmap
          </Heading>
          <Divider />
          <Heading fontSize={['xs', 'sm']} as="h3" textAlign="center">
            How to send feedback
          </Heading>
          <Divider />
          <Heading fontSize={['xs', 'sm']} as="h3" textAlign="center">
            CURRENT LESSONS
          </Heading>
          {lessons.map((lesson: any, idx: number) => (
            <Link key={lesson.slug} href={'/lessons/' + lesson.slug} passHref>
              <ContentBanner lesson={lesson} idx={idx} />
            </Link>
          ))}
        </Stack>
      </Flex>
    </>
  )
}

export default Lessons

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('lessons'))
  const lessons = files.map((filename) => {
    const markdownWithMeta = fs.readFileSync(
      path.join('lessons', filename),
      'utf-8',
    )
    const { data: frontMatter } = matter(markdownWithMeta)
    return {
      frontMatter,
      slug: filename.split('.')[0],
    }
  })
  return {
    props: {
      lessons,
    },
  }
}
